version: '3.8'

services:
  frontend:
    build:
      context: ./ardata-exam-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./ardata-exam-backend
    ports:
      - "8080:8080"
    environment:
      - RUST_ENV=production
    env_file:
      - ./ardata-exam-backend/.env
